#!/usr/bin/env python3
"""Render a monospace TrueType face into a fixed 8x16 bitmap font and emit it
as a C array.

Hand-drawing 95 glyphs is tedious and easy to get subtly wrong, so the font is
generated instead. Antialiasing is deliberately off: at this size a hard
threshold reads more crisply than grey edges, and it keeps each row to one byte.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

CELL_W, CELL_H = 8, 16
FIRST, LAST = 32, 126

CANDIDATES = [
    (r"C:\Windows\Fonts\consola.ttf", 15, 0, -1),
    (r"C:\Windows\Fonts\cour.ttf",    16, 0, -1),
    (r"C:\Windows\Fonts\lucon.ttf",   15, 0, -1),
]


def render(path, size, dx, dy):
    font = ImageFont.truetype(path, size)
    glyphs = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (CELL_W, CELL_H), 0)
        d = ImageDraw.Draw(img)
        d.text((dx, dy), chr(code), font=font, fill=255)
        rows = []
        for y in range(CELL_H):
            bits = 0
            for x in range(CELL_W):
                if img.getpixel((x, y)) >= 128:
                    bits |= 1 << (7 - x)
            rows.append(bits)
        glyphs.append(rows)
    return glyphs


def preview(glyphs, text):
    """Draw a string as text art so the result can be eyeballed before use."""
    lines = ["" for _ in range(CELL_H)]
    for ch in text:
        g = glyphs[ord(ch) - FIRST]
        for y in range(CELL_H):
            lines[y] += "".join("#" if g[y] & (1 << (7 - x)) else "." for x in range(CELL_W))
    return "\n".join(lines)


def coverage(glyphs):
    """How many glyphs actually produced ink. A font rendered at the wrong
    offset silently produces blanks, which is worth catching here."""
    return sum(1 for g in glyphs if any(g))


def main():
    best = None
    for path, size, dx, dy in CANDIDATES:
        try:
            g = render(path, size, dx, dy)
        except OSError:
            continue
        cov = coverage(g)
        # space is legitimately blank, so full coverage is one short
        if best is None or cov > best[1]:
            best = (g, cov, path, size)
        if cov >= (LAST - FIRST):
            break

    if best is None:
        print("no usable font found", file=sys.stderr)
        return 1

    glyphs, cov, path, size = best
    total = LAST - FIRST + 1
    print(f"using {path} at {size}px, {cov}/{total} glyphs inked", file=sys.stderr)
    print(preview(glyphs, "nyx> Hello 123"), file=sys.stderr)

    out = []
    out.append("/* Generated by tools/genfont.py. Do not edit by hand. */")
    out.append('#include "font.h"')
    out.append("")
    out.append(f"const u8 font8x16[{total}][{CELL_H}] = {{")
    for i, g in enumerate(glyphs):
        body = ", ".join(f"0x{b:02X}" for b in g)
        out.append(f"    {{ {body} }},   /* {FIRST + i:3d} {chr(FIRST + i)!r} */")
    out.append("};")
    out.append("")
    open("kernel/font.c", "w").write("\n".join(out))
    print("wrote kernel/font.c", file=sys.stderr)

    # The same glyphs again, as a header. Ring 3 shares nothing with the
    # kernel, so a program that wants to draw text needs its own copy rather
    # than a link to this one.
    u = []
    u.append("/* Generated by tools/genfont.py. Do not edit by hand. */")
    u.append("#pragma once")
    u.append("")
    u.append("#define FONT_W 8")
    u.append(f"#define FONT_H {CELL_H}")
    u.append(f"#define FONT_FIRST {FIRST}")
    u.append(f"#define FONT_LAST  {LAST}")
    u.append("")
    u.append(f"static const unsigned char font8x16[{total}][{CELL_H}] = {{")
    for i, g in enumerate(glyphs):
        body = ", ".join(f"0x{b:02X}" for b in g)
        u.append(f"    {{ {body} }},")
    u.append("};")
    u.append("")
    open("userland/font.h", "w").write("\n".join(u))
    print("wrote userland/font.h", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
